"""Added new columns

Revision ID: a39e55595277
Revises: 431e965cb667
Create Date: 2024-07-26 17:16:00.860191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39e55595277'
down_revision = '431e965cb667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviewsss')
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('new_password')
        batch_op.drop_column('new_passd')
        batch_op.drop_column('new_usename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_usename', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('new_passd', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('new_password', sa.VARCHAR(length=150), nullable=True))

    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)

    op.create_table('reviewsss',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('thumbs_up', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['data.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
